MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  RPN:
    #PRE_NMS_TOPK_TEST: 6000
    #POST_NMS_TOPK_TEST: 1000
    POST_NMS_TOPK_TRAIN: 500
  ROI_HEADS:
    NAME: "Res5ROIHeads"
    #trident roi_heads config
    POSITIVE_FRACTION: 0.5
    BATCH_SIZE_PER_IMAGE: 128
    PROPOSAL_APPEND_GT: False
    NUM_CLASSES: 3
DATASETS:
  ## TRAIN: ("coco_2017_train",)
  ## TEST: ("coco_2017_val",)
  TRAIN: ("ued_trainval",)
  TEST: ("ued_test",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
