MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_vgg_backbone"
  VGG:
    DEPTH: 16
  ANCHOR_GENERATOR:
    SIZES: [[4, 8, 16]]
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
    IN_FEATURES: ['vgg_block4']
  ROI_HEADS:
    NAME: "VggROIHeads"
    IN_FEATURES: ['vgg_block4']
    NUM_CLASSES: 3
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    POOLER_RESOLUTION: 7
DATASETS:
#  TRAIN: ("coco_2017_train",)
#  TEST: ("coco_2017_val",)
  TRAIN: ("ued_trainval",)
  TEST: ("ued_test",)
SOLVER:
  IMS_PER_BATCH: 4
  GAMMA: 0.2
  BASE_LR: 0.0005
  STEPS: (50000, )
  MAX_ITER: 70000
INPUT:
  MIN_SIZE_TRAIN: (600,)
  MIN_SIZE_TEST: 600
  MAX_SIZE_TRAIN: 1000
  MAX_SIZE_TEST: 1000
VERSION: 2